[package]
name = "snow"
version = "0.1.0"
authors = ["cjkenn <cam.j.kennedy@gmail.com>"]

[[bin]]
name = "snow_bin"
path = "./src/snow.rs"

[dependencies]
snowc = { path = "libsnowc" }
vm = { path = "libvm" }
errors = { path = "liberrors" }
types = { path = "libtypes" }