[package]
name = "kolga"
version = "0.1.0"
authors = ["cjkenn"]
edition = "2018"

[[bin]]
name = "kolga_bin"
path = "./src/kolga.rs"

[dependencies]
kolgac = { path = "kolgac" }
gen = { path = "kolgac_codegen" }
error = { path = "kolgac_errors" }
ty = { path = "kolgac_types" }
clap = "3.0.0-beta.1"