[package]
name = "kolgac_llvm"
version = "0.1.0"
authors = ["cjkenn"]
edition = "2018"

[dependencies]
kolgac_errors = { path = "../kolgac_errors" }
kolgac = { path = "../kolgac" }
llvm-sys = "100.2.0"