[package]
name = "kolgac"
version = "0.1.0"
authors = ["cjkenn <cam.j.kennedy@gmail.com>"]

[lib]
name = "kolgac"
path = "lib.rs"

[dependencies]
errors = { path = "../liberrors" }
vm = { path = "../libvm" }