[package]
name = "gen"
version = "0.1.0"
authors = ["cjkenn <cam.j.kennedy@gmail.com>"]

[lib]
name = "gen"
path = "lib.rs"

[dependencies]
error = { path = "../error" }
kolgac = { path = "../kolgac" }
llvm-sys = "100.0.1"